## File Name: RcppExports.R
## File Version: 0.008025
# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mdmb_rcpp_weighted_sd_centered <- function(x, w) {
    .Call('_mdmb_mdmb_rcpp_weighted_sd_centered', PACKAGE='mdmb', x, w)
}

mdmb_rcpp_weighted_sd <- function(x, w) {
    .Call('_mdmb_mdmb_rcpp_weighted_sd', PACKAGE='mdmb', x, w)
}

mdmb_rcpp_lm_wfit <- function(x, y, w) {
    .Call('_mdmb_mdmb_rcpp_lm_wfit', PACKAGE='mdmb', x, y, w)
}

mdmb_rcpp_frm_normalize_posterior <- function(post, case_) {
    .Call('_mdmb_mdmb_rcpp_frm_normalize_posterior', PACKAGE='mdmb', post, case_)
}

mdmb_rcpp_dnorm <- function(x, mu, sigma) {
    .Call('_mdmb_mdmb_rcpp_dnorm', PACKAGE='mdmb', x, mu, sigma)
}

mdmb_test_rtnorm2 <- function(mu, sigma, lower, upper) {
    .Call('_mdmb_mdmb_test_rtnorm2', PACKAGE='mdmb', mu, sigma, lower, upper)
}

