## File Name: RcppExports.R
## File Version: 0.011001
# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mdmb_rcpp_weighted_sd_centered <- function(x, w) {
    .Call('_mdmb_mdmb_rcpp_weighted_sd_centered', PACKAGE='mdmb', x, w)
}

mdmb_rcpp_weighted_sd <- function(x, w) {
    .Call('_mdmb_mdmb_rcpp_weighted_sd', PACKAGE='mdmb', x, w)
}

mdmb_rcpp_lm_wfit <- function(x, y, w) {
    .Call('_mdmb_mdmb_rcpp_lm_wfit', PACKAGE='mdmb', x, y, w)
}

mdmb_rcpp_frm_normalize_posterior <- function(post, case_) {
    .Call('_mdmb_mdmb_rcpp_frm_normalize_posterior', PACKAGE='mdmb', post, case_)
}

mdmb_rcpp_dnorm <- function(x, mu, sigma) {
    .Call('_mdmb_mdmb_rcpp_dnorm', PACKAGE='mdmb', x, mu, sigma)
}

mdmb_rcpp_log_dnorm <- function(x, mu, sigma) {
    .Call('_mdmb_mdmb_rcpp_log_dnorm', PACKAGE='mdmb', x, mu, sigma)
}

mdmb_rcpp_dnorm_double <- function(x, mu, sigma) {
    .Call('_mdmb_mdmb_rcpp_dnorm_double', PACKAGE='mdmb', x, mu, sigma)
}

mdmb_rcpp_log_dnorm_double <- function(x, mu, sigma) {
    .Call('_mdmb_mdmb_rcpp_log_dnorm_double', PACKAGE='mdmb', x, mu, sigma)
}

mdmb_rcpp_oprobit_density <- function(ypred, thresh_low, thresh_upp, y, use_log, eps) {
    .Call('_mdmb_mdmb_rcpp_oprobit_density', PACKAGE='mdmb', ypred, thresh_low, thresh_upp, y, use_log, eps)
}

mdmb_rcpp_oprobit_derivative_ypred <- function(ypred, thresh_low, thresh_upp, y) {
    .Call('_mdmb_mdmb_rcpp_oprobit_derivative_ypred', PACKAGE='mdmb', ypred, thresh_low, thresh_upp, y)
}

mdmb_rcpp_oprobit_derivative_logthresh <- function(ypred, thresh_low, thresh_upp, y, ll0, eps, h, y_value) {
    .Call('_mdmb_mdmb_rcpp_oprobit_derivative_logthresh', PACKAGE='mdmb', ypred, thresh_low, thresh_upp, y, ll0, eps, h, y_value)
}

mdmb_rcpp_oprobit_derivative_logthresh_chain_rule <- function(thresh_der, probs, dens_upp, dens_low, y, eps, y_value) {
    .Call('_mdmb_mdmb_rcpp_oprobit_derivative_logthresh_chain_rule', PACKAGE='mdmb', thresh_der, probs, dens_upp, dens_low, y, eps, y_value)
}

mdmb_rcpp_yj_trafo <- function(y, lambda) {
    .Call('_mdmb_mdmb_rcpp_yj_trafo', PACKAGE='mdmb', y, lambda)
}

mdmb_rcpp_yj_trafo_adjustment_derivative <- function(y, lambda) {
    .Call('_mdmb_mdmb_rcpp_yj_trafo_adjustment_derivative', PACKAGE='mdmb', y, lambda)
}

mdmb_rcpp_yj_trafo_derivative <- function(y, lambda, probit) {
    .Call('_mdmb_mdmb_rcpp_yj_trafo_derivative', PACKAGE='mdmb', y, lambda, probit)
}

